import { Inter } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "./Com/Appsidebar";
const inter = Inter({ subsets: ["latin"] });
import Navbar from "./Com/NavBar";

export const metadata = {
  title: "Reband Lecutres",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` ${inter.className} dark:medium`}>
        <Navbar />
        <SidebarProvider>
          <AppSidebar />
          <main className="min-w-96">
            {" "}
            <SidebarTrigger />
            {children}
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
